doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      spaservice_id: Spalopia\SpaServices\Infrastructure\Persistence\Doctrine\SpaServiceIdType
      timeslot_id: Spalopia\TimeSlots\Infrastructure\Persistence\Doctrine\TimeSlotIdType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    server_version: '15'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Spalopia\SpaServices\Domain:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Spalopia/SpaServices/Infrastructure/Persistence/Doctrine'
        prefix: 'Spalopia\SpaServices\Domain'
      Spalopia\TimeSlots\Domain:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Spalopia/TimeSlots/Infrastructure/Persistence/Doctrine'
        prefix: 'Spalopia\TimeSlots\Domain'

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

    orm:
      enable_lazy_ghost_objects: true

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      enable_lazy_ghost_objects: true
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
