spa-services_get:
  path: /spa-services
  controller: Spalopia\SpaServices\Infrastructure\Http\Controller\GetSpaServicesController
  methods:  [GET]

spa-service-info_get:
  path: /spa-services/{id}
  controller: Spalopia\SpaServices\Infrastructure\Http\Controller\GetSpaServiceInfoController
  methods: [GET]
